# Databases {#databases}

## Downloading Databases

The ELSOC databases are made available to the general public once their review and validation process has been completed. The databases are published and archived in the **Harvard Dataverse** repository, in the [COES data folder](https://dataverse.harvard.edu/dataverse/coes_data_repository). This repository allows free and secure access to the databases.

ELSOC is made available as cross-sectional databases by wave: waves 2016, 2017, 2018, 2019, 2021, and 2022, in R data format (.RData), SPSS (.sav), and Stata 14 (.dta).

Additionally, starting in 2019, the databases are published in longitudinal format to facilitate their use as a panel survey. To date, the longitudinal database of waves 2016-2019 in wide format, and longitudinal databases of waves 2016-2021 and 2016-2022 in wide and long format are published. Variables that have changed over time are harmonized to allow longitudinal use.

As part of a continuous improvement process, it is possible that the published databases are updated during the development of ELSOC, due to the correction of potential errors, improvements in data format, updating of non-response codes, etc. Given this, the latest available version is published in the Harvard Dataverse repository, as well as all previous versions if necessary.

## Technical Sheets

In this section, the Technical Sheet (See Table \@ref(tab:sheet)) is presented, summarizing the main characteristics of the Chilean Social Longitudinal Study (ELSOC COES):

```{r ficha, echo=FALSE, message=FALSE, warning=FALSE}

ficha <- data.frame(caracteristicas = c('Objective', 'Design', 'Instrument', 'Unit of analysis', 'Target population', 'Sampling frame', 'Sampling design', 'Sampling units', 'Periodicity', 'Mode of application', 'Respondent', 'Average duration', 'Representativeness', 'Responsible organization', 'Executing organization'),
                    ELSOC = c('Analyze longitudinally the evolution of conflict and cohesion
                              in Chilean society',
                              'Quantitative study through a structured questionnaire',
                              'Questionnaire composed of closed questions of a simple and multiple nature along with some open questions', 
                              'Individuals',
                              'Men and women aged 18 to 75, habitual residents of private households',
                              'Sampling frame of blocks from the 2011 pre-census, work prepared by the Territorial Intelligence Center (CIT) of the Adolfo Ibáñez University', 
                              'Probabilistic, stratified, by clusters and multi-stage',
                              'First cities are chosen (UPM), then blocks (USM), and sub-blocks and households (UTM). The final selection unit is the person',
                              'Annual. Refreshment sample from the 3rd year',
                              'CAPI format in the respondent\'s home. CATI format during 2021. Mix-mode format in 2022',
                              'Man or woman residing in the household, aged between 18 and 75 years.',
                              '51 minutes',
                              'Approximately 77% of the total population of the country and 93% of the
              urban population with the 2016 Wave sample',
              'Center for Social Conflict and Cohesion Studies (COES)',
              'CentroMicroDatos (CMD) of the University of Chile'))
          

ficha %>% 
  kbl(align = rep('l', 2),
      format = table_format,
      booktabs = TRUE,
      longtable = TRUE,
      col.name = c('Characteristics', 'ELSOC'),
      caption = 'ELSOC COES Technical Sheet') %>% 
  kable_styling(full_width = FALSE,
                latex_options = c('HOLD_position', 'scale_down', 'repeat_header')) %>%
  column_spec(1, width = "8em") %>% 
  column_spec(2, width = "35em") %>% 
  kable_classic_2() 

```


## Database Usage Protocol

Any publication that uses the ELSOC databases, in any of its versions, must cite the source in the following ways (depending on the database used):

- ELSOC 2016:

**Center for Social Conflict and Cohesion Studies (2016). Chilean Social Longitudinal Study, First Wave (ELSOC_W01_v1.00). [Data file]. Santiago, Chile: Center for Social Conflict and Cohesion Studies (COES). www.coes.cl**

- ELSOC 2017:

**Center for Social Conflict and Cohesion Studies (2017). Chilean Social Longitudinal Study, Second Wave (ELSOC_W02_v1.00). [Data file]. Santiago, Chile: Center for Social Conflict and Cohesion Studies (COES). www.coes.cl**

- ELSOC 2018:

**Center for Social Conflict and Cohesion Studies (2018). Chilean Social Longitudinal Study, Third Wave (ELSOC_W03_v1.00). [Data file]. Santiago, Chile: Center for Social Conflict and Cohesion Studies (COES). www.coes.cl**

- ELSOC 2019:

**Center for Social Conflict and Cohesion Studies (2019). Chilean Social Longitudinal Study, Fourth Wave (ELSOC_W04_v1.00). [Data file]. Santiago, Chile: Center for Social Conflict and Cohesion Studies (COES). www.coes.cl**

- ELSOC 2021:

**Center for Social Conflict and Cohesion Studies (2021). Chilean Social Longitudinal Study, Fifth Wave (ELSOC_W05_v1.00). [Data file]. Santiago, Chile: Center for Social Conflict and Cohesion Studies (COES). www.coes.cl**

- ELSOC 2022:

**Center for Social Conflict and Cohesion Studies (2022). Chilean Social Longitudinal Study, Fifth Wave (ELSOC_W06_v1.00). [Data file]. Santiago, Chile: Center for Social Conflict and Cohesion Studies (COES). www.coes.cl**

- ELSOC 2023:

**Center for Social Conflict and Cohesion Studies (2023). Chilean Social Longitudinal Study, Fifth Wave (ELSOC_W07_v1.00). [Data file]. Santiago, Chile: Center for Social Conflict and Cohesion Studies (COES). www.coes.cl**

Or in its longitudinal format:

- Wide Version:

**Center for Social Conflict and Cohesion Studies (2023). Chilean Social Longitudinal Study, Combined Panel Version (ELSOC_Wide). [Data file]. Santiago, Chile: Center for Social Conflict and Cohesion Studies (COES). www.coes.cl**

- Long Version:

**Center for Social Conflict and Cohesion Studies (2023). Chilean Social Longitudinal Study, Combined Panel Version (ELSOC_Long). [Data file]. Santiago, Chile: Center for Social Conflict and Cohesion Studies (COES). www.coes.cl**

Finally, if you wish to cite this User Manual:

**Center for Social Conflict and Cohesion Studies (2023). User Manual of the Chilean Social Longitudinal Study. Santiago, Chile: Center for Social Conflict and Cohesion Studies (COES).**

\newpage

